// src/lib/db.ts
// Singleton MongoDB client — reused across Vercel serverless invocations.

import { MongoClient, Collection, Document } from "mongodb";

const MONGO_URI = process.env.MONGODB_URI || "";

let client: MongoClient | null = null;

async function getClient(): Promise<MongoClient> {
  if (client) return client;
  if (!MONGO_URI) {
    throw new Error(
      "MONGODB_URI is not set. Add it in Vercel Dashboard > Settings > Environment Variables."
    );
  }
  client = new MongoClient(MONGO_URI);
  await client.connect();
  return client;
}

function db() {
  return getClient().then(c => c.db("stiche"));
}

// ─── ORDERS (existing) ───────────────────────────────────────────────
export async function getOrdersCollection(): Promise<Collection<Document>> {
  const c = await getClient();
  return c.db("stiche").collection("orders");
}

// ─── BUSINESS PROFILES ───────────────────────────────────────────────
export interface BusinessProfile {
  sessionId: string;
  shopName: string;
  category: string;           // "crochet" | "food" | "jewellery" | "fashion" | "skincare" | "art" | "homedecor" | "other"
  products: string;           // free text: "bags, wall hangings, baby sets"
  city: string;
  state: string;
  priceMin: number;
  priceMax: number;
  customerType: string;       // "gifting buyers, college girls"
  sellingDuration: string;    // "0-6 months" | "6-24 months" | "2+ years"
  followerRange: string;      // "<500" | "500-5K" | "5K-50K" | "50K+"
  biggestChallenge: string;
  mainGoal: string;
  instagramHandle?: string;
  systemPrompt: string;       // generated by Claude Haiku from above answers
  createdAt: string;
  updatedAt: string;
}

export async function getBusinessProfilesCollection(): Promise<Collection<Document>> {
  const c = await getClient();
  return c.db("stiche").collection("businessProfiles");
}

export async function getBusinessProfile(sessionId: string): Promise<BusinessProfile | null> {
  const col = await getBusinessProfilesCollection();
  const doc = await col.findOne({ sessionId });
  if (!doc) return null;
  const { _id, ...rest } = doc as any;
  return rest as BusinessProfile;
}

export async function saveBusinessProfile(profile: BusinessProfile): Promise<void> {
  const col = await getBusinessProfilesCollection();
  await col.replaceOne(
    { sessionId: profile.sessionId },
    { ...profile, updatedAt: new Date().toISOString() },
    { upsert: true }
  );
}

// ─── SEARCH HISTORY ──────────────────────────────────────────────────
export interface SearchHistoryEntry {
  sessionId: string;
  searchId: string;
  input: {
    topic: string;
    niche: string;
    region: string;
    city?: string;
    goal: string;
  };
  plannedQueries?: any[];
  feedbackEmoji: string | null;      // "love" | "good" | "meh" | "bad" | null
  behaviorScore: number;             // computed from actions
  copiedSections: string[];          // ["hooks", "caption", "hashtags", "pdf"]
  pdfDownloaded: boolean;
  timeOnResultsMs: number;
  topicsSearched: string[];          // for learning engine
  createdAt: string;
}

export async function getSearchHistoryCollection(): Promise<Collection<Document>> {
  const c = await getClient();
  return c.db("stiche").collection("searchHistory");
}

export async function saveSearchHistory(entry: SearchHistoryEntry): Promise<void> {
  const col = await getSearchHistoryCollection();
  await col.replaceOne(
    { searchId: entry.searchId },
    entry,
    { upsert: true }
  );
}

export async function getRecentSearchHistory(sessionId: string, limit = 8): Promise<SearchHistoryEntry[]> {
  const col = await getSearchHistoryCollection();
  const docs = await col
    .find({ sessionId })
    .sort({ createdAt: -1 })
    .limit(limit)
    .toArray();
  return docs.map(({ _id, ...rest }) => rest as SearchHistoryEntry);
}

// ─── LEARNING MEMORY ─────────────────────────────────────────────────
export interface LearningMemory {
  sessionId: string;
  totalSearches: number;
  avgBehaviorScore: number;
  bestPerformingTopics: string[];
  worstPerformingTopics: string[];
  preferredContentStyle: string;    // "emotional" | "curiosity" | "data-driven"
  mostCopiedSection: string;        // "hooks" | "caption" | "hashtags"
  learningLevel: number;            // 1-5
  searchStreak: number;             // consecutive days with a search
  lastSearchDate: string;
  insights: string[];               // plain-language what the AI learned
  updatedAt: string;
}

export async function getLearningMemoryCollection(): Promise<Collection<Document>> {
  const c = await getClient();
  return c.db("stiche").collection("learningMemory");
}

export async function getLearningMemory(sessionId: string): Promise<LearningMemory | null> {
  const col = await getLearningMemoryCollection();
  const doc = await col.findOne({ sessionId });
  if (!doc) return null;
  const { _id, ...rest } = doc as any;
  return rest as LearningMemory;
}

export async function saveLearningMemory(memory: LearningMemory): Promise<void> {
  const col = await getLearningMemoryCollection();
  await col.replaceOne(
    { sessionId: memory.sessionId },
    { ...memory, updatedAt: new Date().toISOString() },
    { upsert: true }
  );
}
